# Generated by Django 5.1.4 on 2025-03-21 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='establishments',
            field=models.CharField(choices=[('FMPC', 'Faculté de Médecine FMPC'), ('UM6', 'Université Mohammed VI')], default='FMPC', help_text="Établissement auquel l'examen est rattaché", max_length=10),
        ),
        migrations.AddField(
            model_name='usersemester',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
