"""
Django settings for QuizLuck project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&5rb(c6_(5)_55$b62lv0*6yymqmb6j9v-)79_y42_!-jpe+gu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.onrender.com']

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quizapp',



]

# Charger les variables d'environnement depuis .env
load_dotenv()

# Récupérer la clé Fernet depuis .env
FERNET_SECRET_KEY = os.getenv("FERNET_SECRET_KEY")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'quizapp.middleware.SemesterValidationMiddleware',

]

ROOT_URLCONF = 'QuizLuck.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'quizapp/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quizapp.context_processors.custom_user_context',  # Ajout de notre context processor

            ],
        },
    },
]

WSGI_APPLICATION = 'QuizLuck.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'quiz_app',
        'USER': 'postgres',
        'PASSWORD': 'Tropintrusive@j',
        'HOST': 'localhost',
        'PORT': '5432',
    },

}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

AUTH_USER_MODEL = 'auth.User'  # Remettre l’utilisateur standard de Django

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',

]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 🔥 Laisse les autres logs actifs
    'handlers': {
        'console': {
            'level': 'DEBUG',  # 🔥 S'assurer que les logs DEBUG apparaissent
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'my_login_view': {  # 🔥 Nom du logger spécifique à la vue
            'handlers': ['console'],
            'level': 'DEBUG',  # 🔥 Assure-toi que le niveau DEBUG est activé
            'propagate': False,  # 🔥 Empêche la propagation à d'autres logs
        },
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',  # Désactive les logs DEBUG globaux de Django
            'propagate': False,
        },
    },
}



LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'     # URL de la page de connexion

LOGOUT_REDIRECT_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_TZ = False  # Désactivez l'utilisation des fuseaux horaires UTC pour utiliser l'heure locale


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "quizapp/static",  # Ajustez ce chemin si nécessaire
    os.path.join(BASE_DIR, 'static'),

]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Par exemple, pour Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nasser.sentissi2@gmail.com'
EMAIL_HOST_PASSWORD = 'zegf ngyv bign pbkq'
